[package]
authors = ["Olger Warnier <olger@spectare.nl>"]
categories = [
  "network-programming",
  "asynchronous",
  "web-programming::http-server",
]
description = "OIDC authentication extractor for Actix 4"
edition = "2021"
keywords = ["actix", "http", "web", "cryptography"]
license = "MIT"
name = "actix-4-jwt-auth"
repository = "https://github.com/spectare/actix-4-jwt-auth"
version = "0.3.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
actix-rt = "2.5.0"
actix-service = "2.0.1"
actix-web = "4.0.0-beta.12"
biscuit = "0.6.0-beta1"
bytes = "1.1.0"
derive_more = "0.99.16"
env_logger = "0.9.0"
futures = "0.3.15"
futures-core = {version = "0.3.7", default-features = false, features = ["alloc"]}
futures-util = {version = "0.3.7", default-features = false, features = ["alloc"]}
log = "0.4.11"
reqwest = {version = "0.11.4", features = ["json", "blocking"]}
sanitize-filename = "0.3"
serde = {version = "1", features = ["derive"]}
serde_derive = "1"
serde_json = "1"
thiserror = "1.0.29"
tokio = {version = "1.6.0", features = ["full"]}

[dev-dependencies]
pretty_assertions = "1.0.0"
